server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview
    username: shrikar
    password: Mukesh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
