openapi: 3.0.3
info:
  title: Learning Security and OpenAPI
  description: |-

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /certificate/create:
    post:
      tags:
        - certificate
      summary: Create custom certificate
      description: Update an existing pet by Id
      operationId: createCert
      requestBody:
        $ref: "#/components/requestBodies/createCertificateRequestBody"
        required: true
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createCertificateResponse'
        '400':
          description: "Metadata malformed or missing"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorBody"
        '403':
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/forbiddenBody"
components:
  requestBodies:
    createCertificateRequestBody:
      description: "Data req for certificate creation request"
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createCertificateRequest'

  schemas:
    createCertificateRequest:
      type: object
      properties:
        certSigningRequest:
          type: string
          format: base64
          minLength: 2
          description: "this the des"

    createCertificateResponse:
      type: object
      properties:
        certificates:
          description: "this the des"
          type: array
          items:
            type: object
            properties:
              data:
                type: string
                description: "Pem certificate format"
                example: "---- BEGIN Certificate----"
    errorBody:
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
    forbiddenBody:
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string